### ISSUE TITLE
searcherにおいて、入力BMSのLEVEL欄が空欄のときにエラーが発生して停止してしまう

### ISSUE THREAD

**Issue by average34** [temtan/bmx2wav#1]
BOFU2017パッケージなどでこの問題を確認。
空欄時には自動で0と解釈するなどの処置を取ることで、エラーなくフォルダごと読み込みができるはず。

**Comment by temtan** [comment]
BMS のヘッダ PLAYLEVEL を空欄した BMS を用意して searcher にて読み込みを行ったのですが、
当該現象は起きませんでした。
出来ればその現象が起きる BMS を調査して教えて頂けないでしょうか？

**Comment by average34** [comment]
フィルタ「BMS系一般」カラム表示「簡易」検索方法「BMS系（フォルダ毎Playlevel最大のみ）」で検索実行すると、#PLAYLEVEL 欄が空欄であったり不正な文字（例：gengaozoA.bmeの#PLAYLEVEL 糞譜面）が含まれている場合にエラー落ちします。
gengaozoはこちらからDL：
http://malie.noor.jp/archive/gengaozo_.rar

#PLAYLEVEL空欄時（そのへんのBOFU2017\\!play\\[!play]DJ.DAI - Faze action(ogg)\\ の#PLAYLEVELのみを書き換えました）：
![image](https://user-images.githubusercontent.com/37168887/108498953-f13daa80-72f0-11eb-93de-e8663560817c.png)
#PLAYLEVEL 糞譜面 時：
![image](https://user-images.githubusercontent.com/37168887/108499256-5d201300-72f1-11eb-81aa-7bda212f1671.png)

**Comment by temtan** [comment]
現象わかりました。正確には
searcherにおいて、検索方法「BMS系（フォルダ毎Playlevel最大のみ）」で検索実行した時に入力BMSのPLAYLEVEL欄が整数値以外であった場合にエラーになる
といった感じですね。
次バージョンより修正しますが、ユーザが直接スクリプトを書き換える事でも修正できます。

bmx2wav_searcher.class.nut の110行目に以下を追加する
      if ( key in entry.bms_data.headers ) {
        // ここ以下追加
        try {
          entry.bms_data.headers[key].tointeger();
        }
        catch ( e ) {
          continue;
        }

**Comment by average34** [comment]
遅ればせながら対応ありがとうございます。無事にBMSファイルの検索および変換を行うことができました。
