### ISSUE TITLE
フォルダ名系変数の追加要望

### ISSUE THREAD

**Issue by Shimi9999** [temtan/bmx2wav#3]
出力ファイル指定テンプレートで使用可能な変数に、以下の2つを追加してほしいです。

- input_bms_directory_basename
  入力BMSファイルがあるフォルダのパスのフォルダ名部分
- input_bms_parent_directory_basename
  入力BMSファイルがあるフォルダの親フォルダのパスのフォルダ名部分

**Comment by temtan** [comment]
言われてみるとこれはあった方が良さそうですね。次のバージョンでは導入しましょう。
