### ISSUE TITLE
リストのファイル出力や再利用の要望

### ISSUE THREAD

**Issue by Nekokan** [temtan/bmx2wav#4]
お世話になっています。
Searcherが便利で大変活躍しています。
使用しているうちに「このような機能が欲しい」と思う部分が出てきました。
というのも、作成された表をcsv, tsvに出力したりコピペを許可したりして、
最終的にはExcelやグーグルスプレッドシートで加工・利用したいです。
あるいはスクリプトや何らかの形で実現可能でしょうか。
その機能があればSearcherで行うBMS整理がすごく楽になりそうです。

**Comment by temtan** [comment]
CSVやTSVでの出力可能です。
以前の他のアプリケーションでリストビューをCSVやTSVに出力する機能を作った事があるので
そこからほぼコピペで行けるかと思いますので次のバージョンで入れましょう。

実装するとしたらファイルメニューに追加でCSVでファイル出力とTSVでクリップボード出力を考えていますが
それでどうでしょうか？CSVでクリップボード出力やTSVでファイル出力等もあった方がよいでしょうか？

**Comment by Nekokan** [comment]
返答ありがとうございます。
・CSVでファイル出力とTSVでクリップボード出力
これで十分やりたいことが行えそうです。
よろしくお願いします。
