### ISSUE TITLE
Suggesting an innovation

### ISSUE THREAD

**Issue by KvadroBlazE** [temtan/bmx2wav#5]
Can you make your program work and output files in 32-bit/64-bit floating point (pcm_f32le/pcm_f64le) .wav formats?

**Comment by temtan** [comment]
それは出来なくは無いですが、それよりも出力されたWAVファイルを他のソフトウェアで変換するようにした方が楽かと思います。BMX2WAVには他のソフトウェアと連携する機能があるのでそれを使えば自動で変換することも出来るかもしれません。

It's possible, but I think it would be easier to convert the output WAV file with other software. BMX2WAV has a function to link with other software, so if you use it, you may be able to convert automatically.

**Comment by KvadroBlazE** [comment]
You talk about upconvert, but I would like to see direct output in floating point format. This is because there is no 0 dB limit and no need to turn down the volume to prevent signal clipping.
