### ISSUE TITLE
ファイル不足でビルドエラー

### ISSUE THREAD

**Issue by Nekokan** [temtan/bmx2wav#8]
独自にビルドできるようになって改造やPRを行えるようになりたいと思い以下の記述を参考にビルドを試みました。
https://bmx2wav.hatenadiary.jp/entry/2020/11/03/202628
必要なものをすべてメイクした後 bmx2wav_searcher をメイクしたところうまくいきました。
一方でbmx2wavは以下のエラーが出てビルドできませんでした。
```
Microsoft(R) Program Maintenance Utility Version 14.29.30153.0
Copyright (C) Microsoft Corporation.  All rights reserved.

	"F:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86\cl.exe" /c /Od /MT /EHsc /W4 /WX /nologo /std:c++latest /Zc:referenceBinding- /I.  /I..\ttl  /I..\tt_squirrel  /I..\tt_squirrel\squirrel3\include  /I.\ogg\libogg\include  /I.\ogg\libvorbis\include -DDEBUG /wd4018  /wd4239  /Yu"Debug_32\stdafx.pch"  /FI"Debug_32\stdafx.pch"  -Fo"Debug_32\mainstay\main_frame.obj" "mainstay\main_frame.cpp"
main_frame.cpp
.\mainstay/main_frame.h(10): fatal error C1083: include ファイルを開けません。'mainstay/settings.h':No such file or directory
NMAKE : fatal error U1077: '"F:\Program Files\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx86\x86\cl.exe"' : リターン コード '0x2'
Stop.

Error End. (2.01 sec)
```
'mainstay/settings.h' がないとのことで、bmx2wav.tdp テキストとして開いて比較すると
mainstay\settings.h
mainstay\settings.cpp
mainstay\settings_property_sheet.h
mainstay\settings_property_sheet.cpp
が不足しています。これらはアップロード忘れでしょうか。それともどこかから入手するものでしょうか。
まずはビルドするためにこれらのファイルを入手したいです。よろしくお願いします。

**Comment by temtan** [comment]
ご指摘の通りアップロード（gitで管理対象に指定するのを）忘れていました。
今しがたアップロードしたのでご確認下さい。

Win32APIという25年以上前のWindowsシステム（現状ネット上で情報が少ない）をベースに
最新の C++（C++20とか）で自作のライブラリを作ってその上で実装するという奇特な事をやっているので、
何かしようとするのは大変かと思いますが、判らない所がありましたら気軽に聞いて下さい。

**Comment by Nekokan** [comment]
確認しました。
無事ビルドできるようになりました。
ここからいろいろいじってみたいと思います。
対応ありがとうございました。
